insert into products (product_name, edible, price, currency, quantity, payment_method, item_type) values('Shark Fin Soup', true , '1500', 'USD', 'per fin', 'bitcoin','meal');
insert into products (product_name, edible, price, currency, quantity, payment_method, item_type) values('Fried Jumbo Jungle Frog', true, '500', 'USD', 'per frog', 'bitcoin','meal' );
insert into products (product_name, edible, price, currency, quantity, payment_method, item_type) values('Tiger Tongue Tater Tots', true, '5000', 'USD', 'per tots', 'bitcoin','side');
insert into products (product_name, edible, price, currency, quantity, payment_method, item_type) values('Beluga Caviar', true, '2000', 'USD', 'per spawn', 'bitcoin', 'side');
insert into products (product_name, edible, price, currency, quantity, payment_method, item_type) values('Gorilla Brain Soup', true, '20000', 'USD', 'per head', 'bitcoin','meal' );
insert into products (product_name, edible, price, currency, quantity, payment_method, item_type) values('Squid Ink Soda', true, '1000', 'USD', 'per bottle', 'bitcoin', 'side' );
insert into products (product_name, edible, price, currency, quantity, payment_method, item_type) values('Rhino Horn', false, '100000', 'USD', 'per horn', 'bitcoin', 'horn/tusk/antler');
insert into products (product_name, edible, price, currency, quantity, payment_method, item_type) values('Elephant Tusk', false, '75000', 'USD', 'per tusk', 'bitcoin', 'horn/tusk/antler' );
insert into products (product_name, edible, price, currency, quantity, payment_method, item_type) values('Deer Antler', false, '5000', 'USD', 'per rack', 'bitcoin', 'horn/tusk/antler');
insert into products (product_name, edible, price, currency, quantity, payment_method, item_type) values('Bullet Ants', false, '1000', 'USD', 'per spawn', 'bitcoin', 'specimen');
insert into products (product_name, edible, price, currency, quantity, payment_method, item_type) values('Ayam Cemani Rooster', false, '2500', 'USD', 'per chicken', 'bitcoin', 'specimen' );
insert into products (product_name, edible, price, currency, quantity, payment_method, item_type) values('White Lion Cub', false, '150000', 'USD', 'per cub', 'bitcoin', 'specimen' );
